"""empty message

Revision ID: b94f434cf645
Revises: 35ae0b426e0e
Create Date: 2023-12-05 03:32:28.930945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b94f434cf645"
down_revision: Union[str, None] = "35ae0b426e0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    role = postgresql.ENUM("user", "admin", "god", name="role")
    role.create(op.get_bind())

    op.add_column(
        "users",
        sa.Column(
            "roles",
            sa.Enum("admin", "user", "god", name="role", create_constraint=True),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "roles")

    role = postgresql.ENUM("user", "admin", "god", name="role")
    role.drop(op.get_bind())
    # ### end Alembic commands ###
