"""empty message

Revision ID: d28789fdcc54
Revises: b94f434cf645
Create Date: 2023-12-05 04:24:58.680217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd28789fdcc54'
down_revision: Union[str, None] = 'b94f434cf645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('admin', 'user', 'god', name='role', create_type=False), nullable=False))
    op.drop_column('users', 'roles')
    op.sync_enum_values('public', 'role', ['admin', 'user', 'god'],
                        [('users', 'role')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'role', ['user', 'admin', 'god'],
                        [('users', 'role')],
                        enum_values_to_rename=[])
    op.add_column('users', sa.Column('roles', postgresql.ENUM('user', 'admin', 'god', name='role', create_type=False), autoincrement=False, nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
